# Generated by Django 4.0 on 2021-12-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_testing_accucracy_remove_testing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='image',
            field=models.ImageField(blank=True, upload_to='test_image', verbose_name='Image'),
        ),
    ]
